language: minimal

env:
    global:
      - HUGO_VERSION=0.62.2
      - DEPLOY_REPO="lobopraveen/praveenlobo.com"
      - ENCRYPTED_KEY=$encrypted_a781b6369385_key
      - ENCRYPTED_IV=$encrypted_a781b6369385_iv

# By defualt depth is set which implies detached head so turn it off
#git:
#  depth: false

install:
# Install hugo
- curl -LO https://github.com/gohugoio/hugo/releases/download/v"${HUGO_VERSION}"/hugo_"${HUGO_VERSION}"_Linux-64bit.deb
- sudo dpkg -i hugo_"${HUGO_VERSION}"_Linux-64bit.deb
- rm -rf hugo_"${HUGO_VERSION}"_Linux-64bit.deb
- hugo version
# Clean the website publish folder 'docs'. Keep media intact
- find docs -mindepth 1 -maxdepth 1 ! -name media -exec rm -rf {} \;
# Run hugo to build the site
- hugo
# Exit if the build is NOT on the DEPLOY REPO
- if [ "$TRAVIS_REPO_SLUG" != "$DEPLOY_REPO" ]; then echo "Not a deploy repo. Exit."; travis_terminate 0; fi
# Exit if the build is due to a pull request
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "Pull request build from $TRAVIS_PULL_REQUEST_BRANCH branch. Exit."; travis_terminate 0; fi
# Exit if the repo is clean i.e. hugo command didn't change any content
- if [ -z "$(git status --porcelain)" ]; then echo "No content change. Exit."; travis_terminate 0; fi
# Decrypt the deploy key
- openssl aes-256-cbc -K "$ENCRYPTED_KEY" -iv "$ENCRYPTED_IV" -in travis_blog_deploy.enc -out travis_blog_deploy -d
- chmod 600 travis_blog_deploy
# Add the deploy key to the keyring
- eval `ssh-agent -s`
- ssh-add travis_blog_deploy
- rm -f travis_blog_deploy
# Set up git parameters
- git config --global user.email "$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- git config --global user.name "$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
# Stash changes
- git stash
# Checkout the branch
- git checkout "$TRAVIS_BRANCH"
# Pop stash
- git stash pop
# Commit the changes to the branch
- git add -A
- git commit -m "Deploy for $TRAVIS_COMMIT. [skip ci]"
# Push the changes to github
- git remote set-url origin git@github.com:"$TRAVIS_REPO_SLUG".git
- git push
- echo "Successfully pushed build results to the GitHub repo."

notifications:
  email:
    on_success: change
    on_failure: always
