language: minimal

env:
    global:
      - HUGO_VERSION=0.62.2
      - DEPLOY_REPO="lobopraveen/praveenlobo.com"

install:
# Install hugo
- curl -LO https://github.com/gohugoio/hugo/releases/download/v"${HUGO_VERSION}"/hugo_"${HUGO_VERSION}"_Linux-64bit.deb
- sudo dpkg -i hugo_"${HUGO_VERSION}"_Linux-64bit.deb
- rm -rf hugo_"${HUGO_VERSION}"_Linux-64bit.deb
- hugo version
# Clean the website publish folder 'docs'. Keep media intact.
- find docs -mindepth 1 -maxdepth 1 ! -name media -exec rm -rf {} \;
# Run hugo to build the site
- hugo
# Commit the generated content if the build is on DEPLOY REPO


- if [ "$TRAVIS_REPO_SLUG" != "DEPLOY_REPO" ]; then travis_terminate 0; fi

- echo "Decrypt the deploy key"
- openssl aes-256-cbc -K "$encrypted_a781b6369385_key" -iv "$encrypted_a781b6369385_iv" -in travis_blog_deploy.enc -out travis_blog_deploy -d
- chmod 600 travis_blog_deploy

- echo "Add the deploy key to the keyring"
- eval `ssh-agent -s`
- ssh-add travis_blog_deploy
- rm -f travis_blog_deploy

- echo "Set up git parameters"
- git config --global user.email "$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- git config --global user.name "$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

- echo "Stash changes"
- git stash

- echo "Checkout correct branch"
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout "$TRAVIS_BRANCH"; else git checkout "$TRAVIS_PULL_REQUEST_BRANCH"; fi

- echo "Pop stash"
- git stash pop
- echo "Commit the changes to the branch"
- git add -A
- git commit -m "Travis deploy for $TRAVIS_COMMIT. [skip ci]"

- echo "Push the changes to github"
- git remote set-url origin git@github.com:"$TRAVIS_REPO_SLUG".git
- git push


notifications:
  email:
    on_success: change
    on_failure: always
