language: minimal

env:
- HUGO_VERSION=0.62.2

install:
# "Step 1 - instaling hugo"
- curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
- sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
- rm -rf hugo_${HUGO_VERSION}_Linux-64bit.deb

before_script:
# "Step 2 - cleaning website publish folder 'docs'. Keeping media intact."
- find docs -mindepth 1 -maxdepth 1 ! -name media -exec rm -rf {} \;
# "Step 3 - building the hugo site"
- hugo version
- hugo
# "Step 4 - decrypting the deploy key"
- openssl aes-256-cbc -K $encrypted_a781b6369385_key -iv $encrypted_a781b6369385_iv -in travis_blog_deploy.enc -out travis_blog_deploy -d
- chmod 600 travis_blog_deploy
# "Step 5 - adding the deploy key to the keyring"
- eval `ssh-agent -s`
- ssh-add travis_blog_deploy
- rm -f travis_blog_deploy
# "Step 6 - setting up git parameters"
- git config --global user.email "lobopraveen@gmail.com"
- git config --global user.name "Travis Deploy"
# "Step 7 - commit the changes to the branch"
- git stash
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout $TRAVIS_BRANCH; else git checkout $TRAVIS_PULL_REQUEST_BRANCH; fi
- git stash pop
- git add -A
- git commit -m "Travis deploy for $TRAVIS_COMMIT. [skip ci]"
# "Step 8 - push the changes to github"
#- git remote set-url origin git@github.com:lobopraveen/praveenlobo.com.git
#- git push
- echo $TRAVIS_REPO_SLUG
- git remote set-url origin git@github.com:$TRAVIS_REPO_SLUG.git
- git push
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- echo "...$COMMITTER_EMAIL..."
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
- echo "...$AUTHOR_NAME..."
# "Successfully built and deployed the site!"

script:
# Travis is failing for no reason. Just having this stage will prevent it from failing.
- echo "Bye!"

notifications:
  email:
    on_success: change
    on_failure: always
