language: minimal

env:
- HUGO_VERSION=0.62.2

install:
# "Step 1 - instaling hugo"
# go get started failing
#- go get github.com/gohugoio/hugo

- curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
- sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

before_script:
# "Step 2 - cleaning website publish folder 'docs'. Keeping media intact.
- find docs -mindepth 1 -maxdepth 1 ! -name media -exec rm -rf {} \;
# "Step 3 - building the hugo site"
- hugo version
- hugo
# "Step 4 - decrypting the deploy key"
- openssl aes-256-cbc -K $encrypted_a781b6369385_key -iv $encrypted_a781b6369385_iv -in travis_blog_deploy.enc -out travis_blog_deploy -d
- chmod 600 travis_blog_deploy
# "Step 5 - adding the deploy key to the keyring"
- eval `ssh-agent -s`
- ssh-add travis_blog_deploy
- rm -f travis_blog_deploy
# "Step 6 - setting up git parameters"
- git config --global user.email "lobopraveen@gmail.com"
- git config --global user.name "Travis Deploy"
# "Step 7 - commit the changes to the branch - $TRAVIS_BRANCH"
- git status
- git branch
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST_BRANCH
- |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
     echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"
     newbranchname=$TRAVIS_BRANCH
  else
     echo "TRAVIS_PULL_REQUEST_BRANCH: $TRAVIS_PULL_REQUEST_BRANCH"
     newbranchname=$TRAVIS_PULL_REQUEST_BRANCH
  fi
- echo "newbranchname: $newbranchname"
#- git stash
#- git checkout $TRAVIS_BRANCH
#- git stash pop
- git add -A
- git commit -m "Travis deploy for $TRAVIS_COMMIT. [skip ci]"
# "Step 8 - push the changes to github if it is not a pull request"
#- git remote set-url origin git@github.com:lobopraveen/praveenlobo.com.git
#- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git push origin; fi
# "Successfully built and deployed the site!"

script:
# Travis is failing for no reason. Just having this stage will prevent it from failing.
- echo "Bye!"

notifications:
  email:
    on_success: change
    on_failure: always
