baseURL = "https://praveenlobo.com/"
title = "Praveen Lobo"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
# "lobopraveen"
googleAnalytics = "UA-20788457-1"

pagination.pagerSize = 10

publishdir = "docs"

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

# See https://praveenlobo.com/blog/hugo-static-site-on-github-customizations/#de-duplicating-the-static-content
[module]
  [[module.mounts]]
    source = "docs"
    target = "static"
  # Adding theme's static directory due to an issue with the minimo theme. See https://github.com/MunifTanjim/minimo/issues/290
  [[module.mounts]]
    source = "themes/minimo/static"
    target = "static"

# Set the unsafe to true as Hugo v0.60 broke shortcodes
[markup.goldmark.renderer]
unsafe = true

[params.info]
description = ""
title404 = "Nothing's here!"

[params.assets]
#favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Praveen Lobo"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Mon, Jan 2, 2006"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "grey"
hideMainMenu = false

[params.sidebar]
enable = false
sticky = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "gmail@praveenlobo.com"
github = "lobopraveen"
gitlab = "lobopraveen"
linkedin = "lobopraveen"
stackoverflow = "319542"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 3
username = "lobopraveen"
repository = "praveenlobo.com"
branch = "master"
enableReCaptcha = true
reCaptchaSiteKey = "6LeSCGoUAAAAADS2jeaiTgzwi_hIQQ2uVumPxpsp"
reCaptchaSecret = "Wb4JOmR/cOt0fkaJ9gKxRarj8ADX1rSsI/jSVhpkNlINwcPCBSSfNKcZrDvQs8sSrQAUPWDILqHpYubB2TFR1raeVjrHuKvwChypXYOQzgN5lIEiL/8dN0UkG9kAc5qbheLJldGnaEiZiDrBTZmCM0kopP+G/MtNjrVXfKvigZo="

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "lobopraveen"
repository = "praveenlobo.com"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[params.social.config]
platforms = ["email","linkedin","github","gitlab","stackoverflow"]

[taxonomies]
#author = "authors"
category = "categories"
#series = "series"
tag = "tags"

[permalinks]
page = "/:contentbasename/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1


[[menu.main]]
  name = "Search"
  url = "/search"
  weight = -1

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 1

[[menu.main]]
  name = "Archive"
  url = "/archive"
  weight = 3

[[menu.main]]
  name = "Reviews"
  url = "/reviews-and-referral-links"
  weight = 2

[[menu.main]]
  name = "Subscribe"
  url = "/subscribe"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 6
