# May-2025: Sourced from https://gohugo.io/host-and-deploy/host-on-github-pages/
name: Build and Deploy Hugo site

on:
  push:
    branches:
      - 'main'
      - 'draft'

  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[deploy]') && !contains(github.event.head_commit.message, '[skip ci]')" # Prevent infinite loop
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.5
      HUGO_ENVIRONMENT: production
      TZ: America/Chicago

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Hugo site
        run: |
          # Clean the website publish folder 'docs'. See https://praveenlobo.com/blog/hugo-static-site-on-github-customizations/#de-duplicating-the-static-content
          find docs -mindepth 1 -maxdepth 1 ! \( -name css -o -name js -o -name media -o -name CNAME \) -exec rm -rf {} \;
          hugo --gc --minify
            

      - name: Push changes to deploy
        run: |
          if [ -z "$(git status --porcelain)" ]; then echo "No changes to deploy. Exiting workflow."; exit 78; fi
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"          
          git add -A
          git commit -m "[deploy] ${GITHUB_SHA::7}"
          git push